### ISSUE TITLE
Error thrown when fetching/parsing list of room users

### ISSUE THREAD

**Issue by samliew** [samliew/chatexchange#191]
I think this has to do with the phantom user (community perhaps?)

![Screenshot_2022-09-09_090938](https://user-images.githubusercontent.com/845988/189252056-feda82e6-c4c9-4562-8218-7dae6dc4b02c.png)

Error message:
```
/app/node_modules/chatexchange/dist/Browser.js:320
        const userId = parseInt($userDiv.attr("href").split("/")[2], 10);
                                                      ^
 
 TypeError: Cannot read properties of undefined (reading 'split')
     at Browser.getTranscript (/app/node_modules/chatexchange/dist/Browser.js:320:54)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async WebsocketEvent._Message_scrapeTranscript (/app/node_modules/chatexchange/dist/Message.js:127:59)
     at async lazy (/app/node_modules/chatexchange/dist/utils.js:34:5)
```

**Comment by Oaphi** [comment]
Fixed in https://github.com/samliew/se-electionbot/commit/fb6b413ad5686882534ec908916b53813de0b3d8, this is not a problem with the library, but with the parsing of empty id sets. Although we should explicitly throw a relevant error when the user is not found, so keeping it open.
