### ISSUE TITLE
The example does not work

### ISSUE THREAD

**Issue by not-a-ethan** [samliew/chatexchange#204]
The example in the README.md file does not work. On line 9 I get the following error:
```
/home/runner/nlnCommentBot/index.js:9
  const myClient = new Client("stackoverflow.com");
                   ^

ReferenceError: Client is not defined
    at main (/home/runner/nlnCommentBot/index.js:9:20)
    at Object.<anonymous> (/home/runner/nlnCommentBot/index.js:54:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

I made sure I copied everything correctly and installed the library. The only thing I changed was the login to my own account. [My GH repo](https://github.com/not-a-ethan/nlnCommentBot/blob/main/index.js).

**Comment by not-a-ethan** [comment]
@Oaphi Thanks. But I don't think I understand what I need to replace to make it work. These is the current lines at the beginning of the file.
```js
const Client = require("chatexchange");

const client = new Client["default"]("stackoverflow.com")

const { ChatEventType } = require("chatexchange");
```

**Comment by Oaphi** [comment]
@not-a-ethan actually, I am not sure what's wrong here, you should be able to do the following (checked out your repo, the hotfix works as expected for me):

```lang-ts
const Client = require("chatexchange");

const { ChatEventType } = require("chatexchange");

const main = async () => {
  const client = new Client['default']("stackoverflow.com");
}
```

**Comment by not-a-ethan** [comment]
@Oaphi Thanks. Now I get a different error with something else.

```js
const botEmail = process.env.botEmail
const botPassWord = process.env.botPassWord

const Client = require("chatexchange");

const { ChatEventType } = require("chatexchange");

const main = async () => {
  const client = new Client['default']("stackoverflow.com");
  
  await client.login(botEmail, botPassWord);

  const me = await client.getMe();

  const myProfile = await client.getProfile(me);

  const { roomCount } = myProfile;
  console.log(`Rooms I am in: ${roomCount}`);

  const room = client.getRoom(167908);

  room.ignore(ChatEventType.FILE_ADDED);

  const joined = await client.joinRoom(room);
  if(joined) {
    room.on("message", async (msg) => {
        console.log("Got Message", msg);

        const { eventType, targetUserId } = msg;

        if (eventType === ChatEventType.USER_MENTIONED && targetUserId === me.id) {
            await msg.reply("Hello World!");
        }

        if(eventType === ChatEventType.USER_LEFT) {
            await msg.send("See you around!", room);
        }
    });

    // Leave the room after five minutes
    setTimeout(async () => {
        await room.sendMessage("Bye everyone!");
        await client.leaveRoom(room);
    }, 3e5);

    // Connect to the room, and listen for new events
    await room.watch();
    return;
  }

  await client.logout();
};

main();
```

```
Rooms I am in: 4
/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Browser.js:308
            throw new ChatExchangeError_1.default(`missing time key for room ${roomid}\n\nTime keys\n${report}`);
                  ^

ChatExchangeError: missing time key for room 167908

Time keys
167908 : missing
    at Browser.watchRoom (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Browser.js:308:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.watch (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Client.js:334:20)
    at async Room.watch (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Room.js:178:52)
```

**Comment by Oaphi** [comment]
@not-a-ethan NP. As for the error, well, when the room is watched, a request is made to SE's `ws-auth` endpoint, which should return a time key. Apparently, it doesn't in your case (as you can see, this is a handled error) - I'll try to reproduce with your setup and see what's up.

**Comment by Oaphi** [comment]
@not-a-ethan I moved the discussion about the time key to a separate issue for bookkeeping. Haven't got time to look at it yet, but I'll try to repro this week.

**Comment by not-a-ethan** [comment]
@Oaphi I see that there was a merge PR but I am still getting the same error without any code changes. I also have the version that includes the changes in that PR

**Comment by Oaphi** [comment]
@not-a-ethan that's normal - there is a separate publishing workflow. I'll (or Samuel if they beat me to it) will be publishing 0.7.5 later today, and the issue will be fixed as soon as that's done. The issue is closed automatically due to the commit mentioning "closes #..."

**Comment by Oaphi** [comment]
@not-a-ethan hmm, do you have version 0.7.5? I see Samuel published the new version. I'll take a look.

**Comment by not-a-ethan** [comment]
@Oaphi It said I had `0.7.5` in one spot but in the `package-lock.json` it said I did not so now I do and it works. Thanks

**Comment by not-a-ethan** [comment]
@Oaphi Played around with it and Im getting another error.

```
/home/runner/nlnCommentBot/index.js:36
            msg.send("See you around!", room);
                ^

TypeError: msg.send is not a function
    at Room.<anonymous> (/home/runner/nlnCommentBot/index.js:36:17)
    at Room.emit (node:events:527:28)
    at Room.emit (node:domain:475:12)
    at WebSocket.<anonymous> (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Client.js:350:25)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at Receiver.receiverOnMessage (/home/runner/nlnCommentBot/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.emit (node:domain:475:12)
```

**Comment by Oaphi** [comment]
@not-a-ethan well, that one's on me :) Sorry about that: there is no method `send` on the `Message` class, that's an error of the example. Thanks for reminding me that I wanted to add a proxy method to the class. I'll move it to a new issue!

**Comment by not-a-ethan** [comment]
@Oaphi Thanks. Now Im not getting any errors with anything right now.
