### ISSUE TITLE
Unable to get a time key from a websocket request when watching a room

### ISSUE THREAD

**Issue by Oaphi** [samliew/chatexchange#207]
@Oaphi Thanks. Now I get a different error with something else.

```js
const botEmail = process.env.botEmail
const botPassWord = process.env.botPassWord

const Client = require("chatexchange");

const { ChatEventType } = require("chatexchange");

const main = async () => {
  const client = new Client['default']("stackoverflow.com");
  
  await client.login(botEmail, botPassWord);

  const me = await client.getMe();

  const myProfile = await client.getProfile(me);

  const { roomCount } = myProfile;
  console.log(`Rooms I am in: ${roomCount}`);

  const room = client.getRoom(167908);

  room.ignore(ChatEventType.FILE_ADDED);

  const joined = await client.joinRoom(room);
  if(joined) {
    room.on("message", async (msg) => {
        console.log("Got Message", msg);

        const { eventType, targetUserId } = msg;

        if (eventType === ChatEventType.USER_MENTIONED && targetUserId === me.id) {
            await msg.reply("Hello World!");
        }

        if(eventType === ChatEventType.USER_LEFT) {
            await msg.send("See you around!", room);
        }
    });

    // Leave the room after five minutes
    setTimeout(async () => {
        await room.sendMessage("Bye everyone!");
        await client.leaveRoom(room);
    }, 3e5);

    // Connect to the room, and listen for new events
    await room.watch();
    return;
  }

  await client.logout();
};

main();
```

```
Rooms I am in: 4
/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Browser.js:308
            throw new ChatExchangeError_1.default(`missing time key for room ${roomid}\n\nTime keys\n${report}`);
                  ^

ChatExchangeError: missing time key for room 167908

Time keys
167908 : missing
    at Browser.watchRoom (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Browser.js:308:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.watch (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Client.js:334:20)
    at async Room.watch (/home/runner/nlnCommentBot/node_modules/chatexchange/dist/Room.js:178:52)
```

_Originally posted by @not-a-ethan in https://github.com/samliew/chatexchange/issues/204#issuecomment-1359519849_

**Comment by Oaphi** [comment]
All right, at least I managed to reproduce the issue with my setup - let's see what is up with *that*.
